title: Long Data
ga_id:

source: jekyll

collections:
- pillars


permalink: pretty

twitter:
  username:

social:
  name: Long Data
  links:

repository: yaworsw/long_data_site
baseurl: ''

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
