title: Long Data
ga_id:

collections:
- pillars

permalink: pretty

twitter:
  username:

social:
  name: Long Data
  links:

repository: long-data/long-data.github.io

sass:
  style: compressed

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag

exclude:
  - src
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
